version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iam_app
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8000:8000"
    
  networks:
    kind:
      external: true
  redis:
    image: redis:7
    container_name: iam_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: iam_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - kind
