apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
      annotations:
        prometheus.io/scrape: "true" 
    spec:
      containers:
      - name: iam
        image: iam-app:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite+aiosqlite:////data/test.db"
        - name: REDIS_URL
          value: "redis://redis:6379" 
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/" 
        volumeMounts:
        - mountPath: /data
          name: sqlite-data
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: sqlite-data
        emptyDir: {}
        